BEGIN;

ALTER TABLE compliance_results
ADD COLUMN IF NOT EXISTS project TEXT,
ADD COLUMN IF NOT EXISTS user_id TEXT,
ADD COLUMN IF NOT EXISTS repo_url TEXT,
ADD COLUMN IF NOT EXISTS file_added JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS file_removed JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS freeze_request BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS feedback TEXT;

COMMIT;
